// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdOe7YiSzxg41w7sMYZKPEYNCxDAwJnk0',
    appId: '1:506515068352:web:f4396a2cc3411bfb656425',
    messagingSenderId: '506515068352',
    projectId: 'vinnovate-830ad',
    authDomain: 'vinnovate-830ad.firebaseapp.com',
    storageBucket: 'vinnovate-830ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgKcexSl36WvMAPunowHf77bpLd05_bH0',
    appId: '1:506515068352:android:693e68f1f388abbf656425',
    messagingSenderId: '506515068352',
    projectId: 'vinnovate-830ad',
    storageBucket: 'vinnovate-830ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7p3Hjxg_56w9naxZJSyN88KwMTt6Tphk',
    appId: '1:506515068352:ios:f6eb64dd729c6cbf656425',
    messagingSenderId: '506515068352',
    projectId: 'vinnovate-830ad',
    storageBucket: 'vinnovate-830ad.appspot.com',
    iosBundleId: 'com.example.vinnovate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7p3Hjxg_56w9naxZJSyN88KwMTt6Tphk',
    appId: '1:506515068352:ios:e87edcc294506017656425',
    messagingSenderId: '506515068352',
    projectId: 'vinnovate-830ad',
    storageBucket: 'vinnovate-830ad.appspot.com',
    iosBundleId: 'com.example.vinnovate.RunnerTests',
  );
}
